import Navbar from "@/components/Navbar";
import localFont from "next/font/local"
import type { Metadata } from "next";
import { Oleo_Script } from 'next/font/google'

import "./globals.css";

const montserrat = localFont({
  src: "./fonts/MontserratVF.ttf",
  variable: "--font-montserrat",
  weight: "100 200 300 400 500 600 700 800 900",
});

const oleo = Oleo_Script({
  variable: "--font-oleo",
  weight: '400',
  subsets: ["latin"], 

});

export const metadata: Metadata = {
  title: "Makabis and Benet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${oleo.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
