import Navbar from "@/components/Navbar";
import localFont from "next/font/local"
import type { Metadata } from "next";
import { Oleo_Script, Quattrocento, Sora } from 'next/font/google'

import "./globals.css";
import Footer from "@/components/Footer";

const montserrat = localFont({
  src: "./fonts/MontserratVF.ttf",
  variable: "--font-montserrat",
  weight: "100 200 300 400 500 600 700 800 900",
});

const oleo = Oleo_Script({
  variable: "--font-oleo",
  weight: '400',
  subsets: ["latin"], 

});

const quattrocento = Quattrocento({
  variable: "--font-quattrocento",
  weight: "400",
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Makabis and Benet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${oleo.variable} ${quattrocento.variable} ${sora.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
